export const PROMO_CODE_TICKET_CHECK_ERROR = {
  NOT_FOUND: 'PROMO_NOT_FOUND',
  EXPIRED: 'PROMO_EXPIRED',
  NOT_FOR_EVENT: 'PROMO_NOT_FOR_EVENT',
  EVENT_NOT_ACTIVE: 'EVENT_NOT_ACTIVE',
  TICKET_LIMIT_REACHED: 'PROMO_TICKET_LIMIT_REACHED',
  TICKET_COUNT_EXCEEDS_REMAINING: 'PROMO_TICKET_COUNT_EXCEEDS_REMAINING',
} as const;
